### ISSUE TITLE
Result is different than Binance technical analysis result

### ISSUE THREAD

**Issue by dineshpazani** [markcheno/go-talib#21]
Could please help with the talib result in golang? It is looks different than the Binance dashboard. I raised the same question in stack overflow: https://stackoverflow.com/questions/68759178/result-is-different-than-binance-technical-analysis-result

**Comment by markcheno** [comment]
I have no idea what library Binance uses to calculate their indicators. Different libraries may have slightly different results. go-talib is based off of the official version of TA-LIB and should match it's results exactly. 

However, please be aware that some indicators have very long lookbacks and final results will vary based on the number of bars input. So in order to properly compare, you would need to use the exact same data and same number of input bars to get a realistic result.

**Comment by davidxiao** [comment]
yeah, the same case,
@dineshpazani , how do you handle it? any luck to resolve it now?
